### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by thefab** [metwork-framework/jinja2_humanize_extension#1]

**Comment by reissmann** [comment]
Hi. Awesome project, thank you for this!

Did you already look into i18n? Any idea whats the best way to do it? I never looked into jinja2 extension development, but as humanize already has i18n support it should "only" be a question of initializing it somehow from the jinja2 end :)

**Comment by thebaptiste** [comment]
I've just added the missing functions : 
- number : ordinal, intcomma, apnumber, fractional, scientific, clamp, metric
- i18n : activate, deactivate, thousands_separator, decimal_separator

**Comment by thebaptiste** [comment]
It's published on pypi in release 0.4.0
